version: "3"

services:

  web:
    build: .
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE

    container_name: web
    volumes:
      - .:/opt/services/project/src
      - ./media:/opt/services/project/media
    ports:
      - 80:8000
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
