version: "3"

services:

  web:
    build: .
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE
    container_name: web
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
