# Generated by Django 3.2.3 on 2021-05-17 07:29

import Profile.validators.birthday_validators
import Profile.validators.phone_number_validators
import Profile.validators.profile_image_validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.TextField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True, validators=[Profile.validators.birthday_validators.age_min_validator, Profile.validators.birthday_validators.age_max_validator])),
                ('phone_number', models.TextField(blank=True, max_length=13, null=True, unique=True, validators=[Profile.validators.phone_number_validators.iran_phone_validate])),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/%m', validators=[Profile.validators.profile_image_validator.profile_image_validate])),
                ('position', models.CharField(choices=[('us', 'User'), ('ad', 'Admin'), ('au', 'Author'), ('su', 'Superuser')], default='us', max_length=2)),
            ],
        ),
    ]
