GENDER_CHOICES = [('m', 'Male'), ('f', 'Female')]
AGE_MIN = 18
AGE_MAX = 100

PHONE_NUMBER_MAX_LENGTH = 13
PROFILE_ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'png', 'gif', 'jpeg']
PROFILE_IMAGE_HEIGHT_MAX = 1000
PROFILE_IMAGE_WIDTH_MAX = 1000
PROFILE_IMAGE_SIZE_MAX = 5  # in MB
PROFILE_IMAGE_HEIGHT_MIN = 128
PROFILE_IMAGE_WIDTH_MIN = 128

