# Generated by Django 3.2.3 on 2021-05-18 16:00

import Tag.validators.tag_image_validators
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(editable=False, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tag/%m', validators=[Tag.validators.tag_image_validators.tag_image_validate])),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('added_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
