# Generated by Django 3.2.3 on 2021-06-19 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='expired_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 19, 5, 11, 33, 961834, tzinfo=utc), null=True),
        ),
    ]
